language: scala

scala:
- 2.10.7
- 2.11.12
- 2.12.8
- 2.12.9
- 2.12.10
- 2.13.0
- 2.13.1

jdk:
- openjdk8
- openjdk11

script:
 - sbt ++${TRAVIS_SCALA_VERSION} test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
